data_name: "230267_Slide2"
r: 50
replicate: "_rep1"
name_truth: "niche"
celltype_name: "cell"
pos_name: ["x", "y"]
tissue_region: "COPD lung tissue"
model_type: "finetunePro_230267_Slide2"
openai_url: "/v1/chat/completions"
use_full_name: false
with_self_type: false
with_region_name: true
Graph_type: "count"
with_negatives: false
with_CoT: false
minimal_f: 0  # this should adjust according to the neighbor_count
top_n: 10  # this should adjust according to the neighbor_count and number of cell types
with_numbers: false
with_domain_name: true
gpt_model: "ft:gpt-4o-mini-2024-07-18:whh:finetunepro-230267-slide2-50:CDde6OfW"
oneshot_prompt: ""
system_prompt: ""
output_type: "niche"
