data_name: "BZ5"
r: 700
name_truth: "niche_truth"
tissue_region: "mPFC region of mice"
model_type: "cluster_end2end"
openai_url: "/v1/chat/completions"
use_full_name: false
with_self_type: false
with_region_name: true
Graph_type: "count"
with_negatives: false
with_CoT: false
minimal_f: 0  # this should adjust according to the neighbor_count
top_n: 99  # this should adjust according to the neighbor_count and number of cell types
with_numbers: true
with_domain_name: true
gpt_model: "gpt-4o-mini"
output_type: "niche"
